// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: book_category.proto

package book_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookCategoryServiceClient is the client API for BookCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookCategoryServiceClient interface {
	Create(ctx context.Context, in *CreateBookCategory, opts ...grpc.CallOption) (*BookCategoryId, error)
	GetAll(ctx context.Context, in *GetAllBookCategoryRequest, opts ...grpc.CallOption) (*GetAllBookCategoryResponse, error)
	GetById(ctx context.Context, in *BookCategoryId, opts ...grpc.CallOption) (*BookCategory, error)
	Update(ctx context.Context, in *BookCategory, opts ...grpc.CallOption) (*MsgResponse, error)
	Delete(ctx context.Context, in *BookCategoryId, opts ...grpc.CallOption) (*MsgResponse, error)
}

type bookCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookCategoryServiceClient(cc grpc.ClientConnInterface) BookCategoryServiceClient {
	return &bookCategoryServiceClient{cc}
}

func (c *bookCategoryServiceClient) Create(ctx context.Context, in *CreateBookCategory, opts ...grpc.CallOption) (*BookCategoryId, error) {
	out := new(BookCategoryId)
	err := c.cc.Invoke(ctx, "/genproto.BookCategoryService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookCategoryServiceClient) GetAll(ctx context.Context, in *GetAllBookCategoryRequest, opts ...grpc.CallOption) (*GetAllBookCategoryResponse, error) {
	out := new(GetAllBookCategoryResponse)
	err := c.cc.Invoke(ctx, "/genproto.BookCategoryService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookCategoryServiceClient) GetById(ctx context.Context, in *BookCategoryId, opts ...grpc.CallOption) (*BookCategory, error) {
	out := new(BookCategory)
	err := c.cc.Invoke(ctx, "/genproto.BookCategoryService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookCategoryServiceClient) Update(ctx context.Context, in *BookCategory, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/genproto.BookCategoryService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookCategoryServiceClient) Delete(ctx context.Context, in *BookCategoryId, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/genproto.BookCategoryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookCategoryServiceServer is the server API for BookCategoryService service.
// All implementations must embed UnimplementedBookCategoryServiceServer
// for forward compatibility
type BookCategoryServiceServer interface {
	Create(context.Context, *CreateBookCategory) (*BookCategoryId, error)
	GetAll(context.Context, *GetAllBookCategoryRequest) (*GetAllBookCategoryResponse, error)
	GetById(context.Context, *BookCategoryId) (*BookCategory, error)
	Update(context.Context, *BookCategory) (*MsgResponse, error)
	Delete(context.Context, *BookCategoryId) (*MsgResponse, error)
	mustEmbedUnimplementedBookCategoryServiceServer()
}

// UnimplementedBookCategoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookCategoryServiceServer struct {
}

func (UnimplementedBookCategoryServiceServer) Create(context.Context, *CreateBookCategory) (*BookCategoryId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBookCategoryServiceServer) GetAll(context.Context, *GetAllBookCategoryRequest) (*GetAllBookCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBookCategoryServiceServer) GetById(context.Context, *BookCategoryId) (*BookCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedBookCategoryServiceServer) Update(context.Context, *BookCategory) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBookCategoryServiceServer) Delete(context.Context, *BookCategoryId) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBookCategoryServiceServer) mustEmbedUnimplementedBookCategoryServiceServer() {}

// UnsafeBookCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookCategoryServiceServer will
// result in compilation errors.
type UnsafeBookCategoryServiceServer interface {
	mustEmbedUnimplementedBookCategoryServiceServer()
}

func RegisterBookCategoryServiceServer(s grpc.ServiceRegistrar, srv BookCategoryServiceServer) {
	s.RegisterService(&BookCategoryService_ServiceDesc, srv)
}

func _BookCategoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookCategoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.BookCategoryService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookCategoryServiceServer).Create(ctx, req.(*CreateBookCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookCategoryService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBookCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookCategoryServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.BookCategoryService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookCategoryServiceServer).GetAll(ctx, req.(*GetAllBookCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookCategoryService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookCategoryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookCategoryServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.BookCategoryService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookCategoryServiceServer).GetById(ctx, req.(*BookCategoryId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookCategoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookCategoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.BookCategoryService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookCategoryServiceServer).Update(ctx, req.(*BookCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookCategoryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookCategoryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookCategoryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.BookCategoryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookCategoryServiceServer).Delete(ctx, req.(*BookCategoryId))
	}
	return interceptor(ctx, in, info, handler)
}

// BookCategoryService_ServiceDesc is the grpc.ServiceDesc for BookCategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookCategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.BookCategoryService",
	HandlerType: (*BookCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BookCategoryService_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BookCategoryService_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _BookCategoryService_GetById_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BookCategoryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BookCategoryService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book_category.proto",
}
